### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by amit-y11** [amit-y11/plant_identifier#1]
Add screenshots from my telegram bot https://t.me/plantidentifybot

**Comment by Lem0naise** [comment]
> Add screenshots from my telegram bot https://t.me/plantidentifybot

I can't figure out how to link the pull request to the issue, but I've updated some grammar.

**Comment by amit-y11** [comment]
Thanks @Lem0naise for contributing , It would have been better if you've added some screenshots of how the bot works. I am merging your pull request though

**Comment by Lem0naise** [comment]
> Thanks @Lem0naise for contributing , It would have been better if you've added some screenshots of how the bot works. I am merging your pull request though

I don't have telegram yet, I will send you some screenshots when I download it.

**Comment by Lem0naise** [comment]
Sending the flower:
![Screenshot_20210219-153400_Telegram](https://user-images.githubusercontent.com/77212082/108525745-5630da80-72c8-11eb-9210-978457d72495.jpg)

Sending multiple pictures of flower:
![Screenshot_20210219-153542_Telegram](https://user-images.githubusercontent.com/77212082/108525787-62b53300-72c8-11eb-9bf0-0f3c2eeafb6a.jpg)

Receiving details of flower:
![Screenshot_20210219-153412_Telegram](https://user-images.githubusercontent.com/77212082/108525847-6d6fc800-72c8-11eb-8226-8966312d924d.jpg)

Flower process menu:
![Screenshot_20210219-153552_Telegram](https://user-images.githubusercontent.com/77212082/108525881-73fe3f80-72c8-11eb-8111-619e80153dc8.jpg)

The grammar still seems to be a bit off but hopefully, you can fix that, unless you want me to. Just change "sended" to "sent."
